//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace XyzTime.AWebTime {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserInfoSoap", Namespace="http://tempuri.org/")]
    public partial class UserInfo : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUserInfoV3OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfoV2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDashboardTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback PutUserTimeLogOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserInfo() {
            this.Url = global::XyzTime.Properties.Settings.Default.XyzTime_AWebTime_UserInfo;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUserInfoV3CompletedEventHandler GetUserInfoV3Completed;
        
        /// <remarks/>
        public event GetUserInfoV2CompletedEventHandler GetUserInfoV2Completed;
        
        /// <remarks/>
        public event GetUserInfoCompletedEventHandler GetUserInfoCompleted;
        
        /// <remarks/>
        public event GetDashboardTokenCompletedEventHandler GetDashboardTokenCompleted;
        
        /// <remarks/>
        public event PutUserTimeLogCompletedEventHandler PutUserTimeLogCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInfoV3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserInfoV3(string str_Email, string str_Password) {
            object[] results = this.Invoke("GetUserInfoV3", new object[] {
                        str_Email,
                        str_Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoV3Async(string str_Email, string str_Password) {
            this.GetUserInfoV3Async(str_Email, str_Password, null);
        }
        
        /// <remarks/>
        public void GetUserInfoV3Async(string str_Email, string str_Password, object userState) {
            if ((this.GetUserInfoV3OperationCompleted == null)) {
                this.GetUserInfoV3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoV3OperationCompleted);
            }
            this.InvokeAsync("GetUserInfoV3", new object[] {
                        str_Email,
                        str_Password}, this.GetUserInfoV3OperationCompleted, userState);
        }
        
        private void OnGetUserInfoV3OperationCompleted(object arg) {
            if ((this.GetUserInfoV3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoV3Completed(this, new GetUserInfoV3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInfoV2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserInfoV2(string str_Email, string str_Password) {
            object[] results = this.Invoke("GetUserInfoV2", new object[] {
                        str_Email,
                        str_Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoV2Async(string str_Email, string str_Password) {
            this.GetUserInfoV2Async(str_Email, str_Password, null);
        }
        
        /// <remarks/>
        public void GetUserInfoV2Async(string str_Email, string str_Password, object userState) {
            if ((this.GetUserInfoV2OperationCompleted == null)) {
                this.GetUserInfoV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoV2OperationCompleted);
            }
            this.InvokeAsync("GetUserInfoV2", new object[] {
                        str_Email,
                        str_Password}, this.GetUserInfoV2OperationCompleted, userState);
        }
        
        private void OnGetUserInfoV2OperationCompleted(object arg) {
            if ((this.GetUserInfoV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoV2Completed(this, new GetUserInfoV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetUserInfo(string str_Email, string str_Password) {
            object[] results = this.Invoke("GetUserInfo", new object[] {
                        str_Email,
                        str_Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoAsync(string str_Email, string str_Password) {
            this.GetUserInfoAsync(str_Email, str_Password, null);
        }
        
        /// <remarks/>
        public void GetUserInfoAsync(string str_Email, string str_Password, object userState) {
            if ((this.GetUserInfoOperationCompleted == null)) {
                this.GetUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoOperationCompleted);
            }
            this.InvokeAsync("GetUserInfo", new object[] {
                        str_Email,
                        str_Password}, this.GetUserInfoOperationCompleted, userState);
        }
        
        private void OnGetUserInfoOperationCompleted(object arg) {
            if ((this.GetUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoCompleted(this, new GetUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDashboardToken", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDashboardToken(string str_UserToken) {
            object[] results = this.Invoke("GetDashboardToken", new object[] {
                        str_UserToken});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDashboardTokenAsync(string str_UserToken) {
            this.GetDashboardTokenAsync(str_UserToken, null);
        }
        
        /// <remarks/>
        public void GetDashboardTokenAsync(string str_UserToken, object userState) {
            if ((this.GetDashboardTokenOperationCompleted == null)) {
                this.GetDashboardTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDashboardTokenOperationCompleted);
            }
            this.InvokeAsync("GetDashboardToken", new object[] {
                        str_UserToken}, this.GetDashboardTokenOperationCompleted, userState);
        }
        
        private void OnGetDashboardTokenOperationCompleted(object arg) {
            if ((this.GetDashboardTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDashboardTokenCompleted(this, new GetDashboardTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PutUserTimeLog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PutUserTimeLog(string UserId, string AppName, string AppTitle, string AppData, string LogOn, int KeyStroke, int MouseClick, int MouseMove, int TimeSec) {
            this.Invoke("PutUserTimeLog", new object[] {
                        UserId,
                        AppName,
                        AppTitle,
                        AppData,
                        LogOn,
                        KeyStroke,
                        MouseClick,
                        MouseMove,
                        TimeSec});
        }
        
        /// <remarks/>
        public void PutUserTimeLogAsync(string UserId, string AppName, string AppTitle, string AppData, string LogOn, int KeyStroke, int MouseClick, int MouseMove, int TimeSec) {
            this.PutUserTimeLogAsync(UserId, AppName, AppTitle, AppData, LogOn, KeyStroke, MouseClick, MouseMove, TimeSec, null);
        }
        
        /// <remarks/>
        public void PutUserTimeLogAsync(string UserId, string AppName, string AppTitle, string AppData, string LogOn, int KeyStroke, int MouseClick, int MouseMove, int TimeSec, object userState) {
            if ((this.PutUserTimeLogOperationCompleted == null)) {
                this.PutUserTimeLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPutUserTimeLogOperationCompleted);
            }
            this.InvokeAsync("PutUserTimeLog", new object[] {
                        UserId,
                        AppName,
                        AppTitle,
                        AppData,
                        LogOn,
                        KeyStroke,
                        MouseClick,
                        MouseMove,
                        TimeSec}, this.PutUserTimeLogOperationCompleted, userState);
        }
        
        private void OnPutUserTimeLogOperationCompleted(object arg) {
            if ((this.PutUserTimeLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PutUserTimeLogCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetUserInfoV3CompletedEventHandler(object sender, GetUserInfoV3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoV3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoV3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetUserInfoV2CompletedEventHandler(object sender, GetUserInfoV2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetUserInfoCompletedEventHandler(object sender, GetUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetDashboardTokenCompletedEventHandler(object sender, GetDashboardTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDashboardTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDashboardTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void PutUserTimeLogCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591